#coding=utf-8

from django.utils.translation import ugettext_lazy as _

ALBUM_IMAGES_QTY = 20
ALBUM_IMAGES_SIZE = 20 * 1024 * 1024

GENDER_CHOICES = (
  ('', _('gender')),
  (1, _('Male')),
  (2, _('Female')),
)

PROFESSION_CHOICES = (
  ('', _('profession')),
  (1, _('Student')),
  (2, _('Engineer')),
  (3, _('Artist')),
  (4, _('Performer')),
  (5, _('Manager')),
  (6, _('Doctor')),
  (7, _('Civilian')),
  (8, _('Accountant')),
  (9, _('Lawyer')),
  (10, _('Freelancer')),
  (11, _('Others')),
)

SERVICE_TYPE_CHOICES = (
  (1, _('Part time')),
  (2, _('Full time')),
)

SERVICE_PRICE_TYPE_CHOICES = (
  (1, _('day')),
  (2, _('hour')),
  (3, _('time')),
)

SERVICE_CURRENCY_CHOICES = (
  (1, _('€')),
  (2, _('¥')),
)

BOOKING_STATUS = (
  (1, _('Negotiation by customer')),
  (2, _('Negotiation by provider')),
  (3, _('Rejected by customer')),
  (4, _('Rejected by provider')),
  (5, _('Approved by customer')),
  (6, _('Approved by provider')),
  (7, _('Deleted by customer')),
  (8, _('Deleted by provider')),
  (9, _('Canceled by customer')),
  (10, _('Canceled by provider')),
)

SERVICE_STATUS = (
  (1, _('Moderation')),
  (2, _('Active')),
  (3, _('Not active')),
)

PROFILE_STATUS = (
  (1, _('Moderation')),
  (2, _('Active')),
  (3, _('Not active')),
  (4, _('Suspended')),
)

ALBUM_IMAGE_STATUS = SERVICE_STATUS

IDENTIFICATION_STATUS = (
  (1, _('Not started')),
  (2, _('Waiting for approval')),
  (3, _('Approved')),
  (4, _('Declined')),
)

MUGSHOT_SETTINGS = {'size': (140, 140), 'crop': 'smart'}

SERVICE_CARD_IMAGE_SETTINGS = {'size': (800, 600), 'crop': 'smart'}

PROFILE_CARD_IMAGE_SETTINGS = {'size': (800, 600), 'crop': 'smart'}

ASSIGNED_PERMISSIONS = {
  'profile':
    (('view_profile', 'Can view profile'),
     ('change_profile', 'Can change profile'),
     ('delete_profile', 'Can remove profile')),
  'user':
    (('change_user', 'Can change user'),
     ('delete_user', 'Can delete user')),
  'contact':
    (('view_contact', 'Can view contact'),
     ('change_contact', 'Can change contact'),
     ('delete_contact', 'Can remove contact')),
  'service':
    (('add_service', 'Can add service'),
     ('view_service', 'Can view service'),
     ('change_service', 'Can change service'),
     ('delete_service', 'Can delete service')),
  'message':
    (('add_message', 'Can add message'),
     ('view_message', 'Can view message'),
     ('change_message', 'Can change message'),
     ('delete_message', 'Can delete message')),
  'booking_sender':
    (('add_booking', 'Can add booking'),
     ('view_booking', 'Can view booking'),
     ('change_booking', 'Can change booking'),
     ('delete_booking', 'Can delete booking'),
     ('reject_booking', 'Can reject booking'),
     ('cancel_booking', 'Can cancel booking'),
     ('approve_booking', 'Can approve booking')),

   'booking_recipient':
    (('add_booking', 'Can add booking'),
     ('view_booking', 'Can view booking'),
     ('change_booking', 'Can change booking'),
     ('delete_booking', 'Can delete booking'),
     ('reject_booking', 'Can reject booking'),
     ('cancel_booking', 'Can cancel booking'),
     ('approve_booking', 'Can approve booking')),


}

GLOBAL_PERMISSIONS = {
  'global':
    (('insite_messages.add_message', 'Can add message'),
     ('insite_messages.view_message', 'Can view message'),
     ('insite_messages.change_message', 'Can change message'),
     ('insite_messages.delete_message', 'Can delete message'),

     ('services.add_service', 'Can add service'),
     ('services.view_service', 'Can view service'),
     ('services.change_service', 'Can change service'),
     ('services.delete_service', 'Can delete service'),

     ('bookings.add_booking', 'Can add booking'),
     ('bookings.view_booking', 'Can view booking'),
     ('bookings.change_booking', 'Can change booking'),
     ('bookings.reject_booking', 'Can reject booking'),
     ('bookings.delete_booking', 'Can delete booking'),
     ('bookings.approve_booking', 'Can approve booking'),
     ('bookings.cancel_booking', 'Can cancel booking'),

    ('followship.view_followers', 'Can view followers'),
    ('followship.view_followings', 'Can view followings')),
}

COUNTRY_OF_BIRTH = (
  ('', _('Country of birth')),
  (1, _('Afghanistan')),
  (2, _('Aland Islands')),
  (3, _('Albania')),
  (4, _('Algeria')),
  (5, _('American Samoa')),
  (6, _('Andorra')),
  (7, _('Angola')),
  (8, _('Anguilla')),
  (9, _('Antigua')),
  (10, _('Argentina')),
  (11, _('Armenia')),
  (12, _('Aruba')),
  (13, _('Australia')),
  (14, _('Austria')),
  (15, _('Azerbaijan')),
  (16, _('Bahamas')),
  (17, _('Bahrain')),
  (18, _('Bangladesh')),
  (19, _('Barbados')),
  (20, _('Belarus')),
  (21, _('Belgium')),
  (22, _('Belize')),
  (23, _('Benin')),
  (24, _('Bermuda')),
  (25, _('Bhutan')),
  (26, _('Bolivia')),
  (27, _('Bosnia')),
  (28, _('Botswana')),
  (29, _('Bouvet Island')),
  (30, _('Brazil')),
  (31, _('British Virgin Islands')),
  (32, _('Brunei')),
  (33, _('Bulgaria')),
  (34, _('Burkina Faso')),
  (35, _('Burma')),
  (36, _('Burundi')),
  (37, _('Caicos Islands')),
  (38, _('Cambodia')),
  (39, _('Cameroon')),
  (40, _('Canada')),
  (41, _('Cape Verde')),
  (42, _('Cayman Islands')),
  (43, _('Central African Republic')),
  (44, _('Chad')),
  (45, _('Chile')),
  (46, _('China')),
  (47, _('Christmas Island')),
  (48, _('Cocos Islands')),
  (49, _('Colombia')),
  (50, _('Comoros')),
  (51, _('Congo Brazzaville')),
  (52, _('Congo')),
  (53, _('Cook Islands')),
  (54, _('Costa Rica')),
  (55, _('Cote Divoire')),
  (56, _('Croatia')),
  (57, _('Cuba')),
  (58, _('Cyprus')),
  (59, _('Czech Republic')),
  (60, _('Denmark')),
  (61, _('Djibouti')),
  (62, _('Dominica')),
  (63, _('Dominican Republic')),
  (64, _('Ecuador')),
  (65, _('Egypt')),
  (66, _('El Salvador')),
  (67, _('England')),
  (68, _('Equatorial Guinea')),
  (69, _('Eritrea')),
  (70, _('Estonia')),
  (71, _('Ethiopia')),
  (72, _('European Union')),
  (73, _('Falkland Islands')),
  (74, _('Faroe Islands')),
  (75, _('Fiji')),
  (76, _('Finland')),
  (77, _('France')),
  (78, _('French Guiana')),
  (79, _('French Polynesia')),
  (80, _('French Territories')),
  (81, _('Gabon')),
  (82, _('Gambia')),
  (83, _('Georgia')),
  (84, _('Germany')),
  (85, _('Ghana')),
  (86, _('Gibraltar')),
  (87, _('Greece')),
  (88, _('Greenland')),
  (89, _('Grenada')),
  (90, _('Guadeloupe')),
  (91, _('Guam')),
  (92, _('Guatemala')),
  (93, _('Guinea-Bissau')),
  (94, _('Guinea')),
  (95, _('Guyana')),
  (96, _('Haiti')),
  (97, _('Heard Island')),
  (98, _('Honduras')),
  (99, _('Hong Kong')),
  (100, _('Hungary')),
  (101, _('Iceland')),
  (102, _('India')),
  (103, _('Indian Ocean Territory')),
  (104, _('Indonesia')),
  (105, _('Iran')),
  (106, _('Iraq')),
  (107, _('Ireland')),
  (108, _('Israel')),
  (109, _('Italy')),
  (110, _('Jamaica')),
  (111, _('Japan')),
  (112, _('Jordan')),
  (113, _('Kazakhstan')),
  (114, _('Kenya')),
  (115, _('Kiribati')),
  (116, _('Kuwait')),
  (117, _('Kyrgyzstan')),
  (118, _('Laos')),
  (119, _('Latvia')),
  (120, _('Lebanon')),
  (121, _('Lesotho')),
  (122, _('Liberia')),
  (123, _('Libya')),
  (124, _('Liechtenstein')),
  (125, _('Lithuania')),
  (126, _('Luxembourg')),
  (127, _('Macau')),
  (128, _('Macedonia')),
  (129, _('Madagascar')),
  (130, _('Malawi')),
  (131, _('Malaysia')),
  (132, _('Maldives')),
  (133, _('Mali')),
  (134, _('Malta')),
  (135, _('Marshall Islands')),
  (136, _('Martinique')),
  (137, _('Mauritania')),
  (138, _('Mauritius')),
  (139, _('Mayotte')),
  (140, _('Mexico')),
  (141, _('Micronesia')),
  (142, _('Moldova')),
  (143, _('Monaco')),
  (144, _('Mongolia')),
  (145, _('Montenegro')),
  (146, _('Montserrat')),
  (147, _('Morocco')),
  (148, _('Mozambique')),
  (149, _('Namibia')),
  (150, _('Nauru')),
  (151, _('Nepal')),
  (152, _('Netherlands Antilles')),
  (153, _('Netherlands')),
  (154, _('New Caledonia')),
  (155, _('New Guinea')),
  (156, _('New Zealand')),
  (157, _('Nicaragua')),
  (158, _('Niger')),
  (159, _('Nigeria')),
  (160, _('Niue')),
  (161, _('Norfolk Island')),
  (162, _('North Korea')),
  (163, _('Northern Mariana Islands')),
  (164, _('Norway')),
  (165, _('Oman')),
  (166, _('Pakistan')),
  (167, _('Palau')),
  (168, _('Palestine')),
  (169, _('Panama')),
  (170, _('Paraguay')),
  (171, _('Peru')),
  (172, _('Philippines')),
  (173, _('Pitcairn Islands')),
  (174, _('Poland')),
  (175, _('Portugal')),
  (176, _('Puerto Rico')),
  (177, _('Qatar')),
  (178, _('Reunion')),
  (179, _('Romania')),
  (180, _('Russia')),
  (181, _('Rwanda')),
  (182, _('Saint Helena')),
  (183, _('Saint Kitts and Nevis')),
  (184, _('Saint Lucia')),
  (185, _('Saint Pierre')),
  (186, _('Saint Vincent')),
  (187, _('Samoa')),
  (188, _('San Marino')),
  (189, _('Sandwich Islands')),
  (190, _('Sao Tome')),
  (191, _('Saudi Arabia')),
  (192, _('Senegal')),
  (193, _('Serbia')),
  (194, _('Serbia')),
  (195, _('Seychelles')),
  (196, _('Sierra Leone')),
  (197, _('Singapore')),
  (198, _('Slovakia')),
  (199, _('Slovenia')),
  (200, _('Solomon Islands')),
  (201, _('Somalia')),
  (202, _('South Africa')),
  (203, _('South Korea')),
  (204, _('Spain')),
  (205, _('Sri Lanka')),
  (206, _('Sudan')),
  (207, _('Suriname')),
  (208, _('Svalbard')),
  (209, _('Swaziland')),
  (210, _('Sweden')),
  (211, _('Switzerland')),
  (212, _('Syria')),
  (213, _('Taiwan')),
  (214, _('Tajikistan')),
  (215, _('Tanzania')),
  (216, _('Thailand')),
  (217, _('Timorleste')),
  (218, _('Togo')),
  (219, _('Tokelau')),
  (220, _('Tonga')),
  (221, _('Trinidad')),
  (222, _('Tunisia')),
  (223, _('Turkey')),
  (224, _('Turkmenistan')),
  (225, _('Tuvalu')),
  (226, _('Uganda')),
  (227, _('Ukraine')),
  (228, _('United Arab Emirates')),
  (229, _('United States')),
  (230, _('Uruguay')),
  (231, _('Us Minor Islands')),
  (232, _('Us Virgin Islands')),
  (233, _('Uzbekistan')),
  (234, _('Vanuatu')),
  (235, _('Vatican City')),
  (236, _('Venezuela')),
  (237, _('Vietnam')),
  (238, _('Wallis and Futuna')),
  (239, _('Western Sahara')),
  (240, _('Yemen')),
  (241, _('Zambia')),
  (242, _('Zimbabwe')),
)
MARRITTAL_STATUS = (
  ('', _('marrittal_status')),
  (1, _('unmarried')),
  (2, _('married')),
  (3, _('divorced')),
  (4, _('widowed')),
  (5, _('separated')),
  (6, _('no answer')),
)
CHILDREN = (
  ('', _('children')),
  (1, _('no kid')),
  (2, _('one kid')),
  (3, _('> 1 kid')),
  (4, _('no answer')),
)
ETHNICITY = (
  ('', _('ethnicity')),
  (1, _('chinese')),
  (2, _('cambodian')),
  (3, _('filipino')),
  (4, _('japanese')),
  (5, _('korean')),
  (6, _('malaysian')),
  (7, _('thai')),
  (8, _('vietnamese')),
  (9, _('indian')),
  (10, _('black')),
  (11, _('hispanic latin')),
  (12, _('middle east')),
  (13, _('white/caucasian')),
  (14, _('other')),
  (15, _('no answer')),
)
RELIGION = (
  ('', _('religion')),
  (1, _('buddihism')),
  (2, _('chistianity')),
  (3, _('judaism')),
  (4, _('catholicism')),
  (5, _('islan')),
  (6, _('hinduism')),
  (7, _('other')),
  (8, _('no answer')),
)
EDUCATION = (
  ('', _('education')),
  (1, _('high school')),
  (2, _('bachelor')),
  (3, _('master')),
  (4, _('phd')),
  (5, _('no answer')),
)
ANNUAL_INCOME = (
  ('', _('annual_income')),
  (1, _('< €15k')),
  (2, _('€15k - €30k')),
  (3, _('€30k - €40k')),
  (4, _('€40k - €50k')),
  (5, _('€50k - €80k')),
  (6, _('> €80k')),
  (7, _('no answer')),
)
IMMIGRATION_STATUS = (
  ('', _('immigration_status')),
  (1, _('resident')),
  (2, _('citizen')),
  (3, _('no answer')),
)
BODY_FORM = (
  ('', _('body_form')),
  (1, _('slim')),
  (2, _('athlete')),
  (3, _('average')),
  (4, _('curvy')),
  (5, _('no answer')),
)
SMOKING = (
  ('', _('smoking')),
  (1, _('yes')),
  (2, _('some times')),
  (3, _('never')),
  (4, _('no answer')),
)
DRINKING = (
  ('', _('drinking')),
  (1, _('yes')),
  (2, _('some times')),
  (3, _('never')),
  (4, _('no answer')),
)
PETS = (
  ('', _('pets')),
  (1, _('dog(s)')),
  (2, _('cat(s)')),
  (3, _('other pets')),
  (4, _('want to have')),
  (5, _('no answer')),
)
HOBBY = (
  ('', _('hobby')),
  (1, _('basketball')),
  (2, _('camping')),
  (3, _('card game')),
  (4, _('bicycle')),
  (5, _('dance')),
  (6, _('fishing/hunting')),
  (7, _('golf')),
  (8, _('musical')),
  (9, _('jogging')),
  (10, _('singing')),
  (11, _('ski')),
  (12, _('football')),
  (13, _('read')),
  (14, _('swimming')),
  (15, _('tennis')),
  (16, _('travel')),
  (17, _('gym')),
  (18, _('yoga')),
  (19, _('Other')),
)
